apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-taint
   # these are replica set labels
  labels:
    purpose: taint-demo
    project: roboshop

spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: taint-demo
      project: roboshop   
  template:
    metadata:
    ## pod labels
      labels:
        purpose: taint-demo
        project: roboshop  
    spec:
      containers:
      - name: nginx
        image: nginx
