apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
spec:
   affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      ## hard rule
        nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - us-east-1d
              - key: disktype
                operator: In
                values:    
                - ssd   
      # preferredDuringSchedulingIgnoredDuringExecution:
      # ## soft rule
      # - weight: 50
      #   preference:
      #     matchExpressions:
      #     - key: project
      #       operator: In
      #       values:
      #       - roboshop
      # - weight: 10
      #   preference:
      #     matchExpressions:
      #     - key: project
      #       operator: In
      #       values:
      #       - amazon
   containers:
   - name: nginx
     image: nginx
     imagePullPolicy: Always
